### ISSUE TITLE
Unit and integration tests

### ISSUE THREAD

**Issue by jakubsolecki** [agh-docker-monitoring/dockiera-app#118]
There are a many components that are not tested at all.

- [x] Check existing and add missing tests form model classes/mechanisms
- [ ] Cover more edge cases that should trigger Alerts mechanism
- [ ] Test sending alerts upon violating all kind of rules (mockito spy + check proper method calls)
- [ ] InfluxDbProxy tests - mock static methods form Influx library
- [ ] MetricService tests
- [ ] AliveHostGuard tests

If you know other missing tests feel free to add them here.
