### ISSUE TITLE
Refactor addHost dialog

### ISSUE THREAD

**Issue by kraleppa** [agh-docker-monitoring/dockiera-app#61]
We should refactor addHost dialog:

- [ ] Work with the new API
- [ ] We should use the useForm hook (it should work now because we dialog to seperate route
- [ ] Styling (especially range pickers)
- [ ] Refactor range pickers (it's really bad implemented right now for example warn level might be higher than crit I guess)
- [ ] Additional range picker on cpu usage
